openapi: 3.0.3
info:
  title: QuetzalShip Gateway API
  description: API Gateway para el sistema de envíos QuetzalShip
  version: 2.0.0
  contact:
    name: QuetzalShip Team

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /v1/orders:
    post:
      summary: Crear una nueva orden
      operationId: createOrder
      tags:
        - Orders
      parameters:
        - name: Idempotency-Key
          in: header
          required: false
          description: Clave de idempotencia para evitar duplicados
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Orden creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto de idempotencia
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Servicio no disponible
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: Listar órdenes
      operationId: listOrders
      tags:
        - Orders
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Lista de órdenes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOrdersResponse'

  /v1/orders/{orderId}:
    get:
      summary: Obtener detalle de una orden
      operationId: getOrder
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalle de la orden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetail'
        '404':
          description: Orden no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/orders/{orderId}/cancel:
    post:
      summary: Cancelar una orden
      operationId: cancelOrder
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Orden cancelada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelOrderResponse'
        '404':
          description: Orden no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: La orden ya está cancelada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/orders/{orderId}/receipt:
    get:
      summary: Obtener recibo de una orden
      operationId: getReceipt
      tags:
        - Orders
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recibo generado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
        '404':
          description: Orden no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: "ok"
        timestamp:
          type: string
          format: date-time
        services:
          type: object
          properties:
            orders:
              type: string
              example: "healthy"
            pricing:
              type: string
              example: "healthy"
            receipt:
              type: string
              example: "healthy"

    Zone:
      type: string
      enum:
        - METRO
        - INTERIOR
        - FRONTERA

    ServiceType:
      type: string
      enum:
        - STANDARD
        - EXPRESS
        - SAME_DAY

    OrderStatus:
      type: string
      enum:
        - ACTIVE
        - CANCELLED

    DiscountType:
      type: string
      enum:
        - NONE
        - PERCENT
        - FIXED

    Package:
      type: object
      required:
        - weightKg
        - heightCm
        - widthCm
        - lengthCm
        - fragile
        - declaredValueQ
      properties:
        weightKg:
          type: number
          minimum: 0.01
          example: 5.5
        heightCm:
          type: number
          minimum: 0.01
          example: 30
        widthCm:
          type: number
          minimum: 0.01
          example: 20
        lengthCm:
          type: number
          minimum: 0.01
          example: 15
        fragile:
          type: boolean
          example: false
        declaredValueQ:
          type: number
          minimum: 0
          example: 500

    Discount:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/DiscountType'
        value:
          type: number
          minimum: 0
          example: 10

    Breakdown:
      type: object
      properties:
        orderBillableKg:
          type: number
          example: 5.5
        baseSubtotal:
          type: number
          example: 44.00
        serviceSubtotal:
          type: number
          example: 44.00
        fragileSurcharge:
          type: number
          example: 0
        insuranceSurcharge:
          type: number
          example: 12.50
        subtotalWithSurcharges:
          type: number
          example: 56.50
        discountAmount:
          type: number
          example: 5.65
        total:
          type: number
          example: 50.85
        ratePerKg:
          type: number
          example: 8
        serviceMultiplier:
          type: number
          example: 1.0
        fragilePackagesCount:
          type: integer
          example: 0
        declaredValueTotal:
          type: number
          example: 500

    CreateOrderRequest:
      type: object
      required:
        - originZone
        - destinationZone
        - serviceType
        - packages
        - insuranceEnabled
      properties:
        originZone:
          $ref: '#/components/schemas/Zone'
        destinationZone:
          $ref: '#/components/schemas/Zone'
        serviceType:
          $ref: '#/components/schemas/ServiceType'
        packages:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Package'
        discount:
          $ref: '#/components/schemas/Discount'
        insuranceEnabled:
          type: boolean
          example: false

    CreateOrderResponse:
      type: object
      properties:
        orderId:
          type: string
          example: "ord_abc123"
        status:
          $ref: '#/components/schemas/OrderStatus'
        createdAt:
          type: string
          format: date-time
        breakdown:
          $ref: '#/components/schemas/Breakdown'
        total:
          type: number
          example: 50.85

    OrderSummary:
      type: object
      properties:
        orderId:
          type: string
        destinationZone:
          $ref: '#/components/schemas/Zone'
        serviceType:
          $ref: '#/components/schemas/ServiceType'
        status:
          $ref: '#/components/schemas/OrderStatus'
        total:
          type: number
        createdAt:
          type: string
          format: date-time

    ListOrdersResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderSummary'
        totalCount:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer

    OrderDetail:
      type: object
      properties:
        orderId:
          type: string
        createdAt:
          type: string
          format: date-time
        originZone:
          $ref: '#/components/schemas/Zone'
        destinationZone:
          $ref: '#/components/schemas/Zone'
        serviceType:
          $ref: '#/components/schemas/ServiceType'
        packages:
          type: array
          items:
            $ref: '#/components/schemas/Package'
        discount:
          $ref: '#/components/schemas/Discount'
        insuranceEnabled:
          type: boolean
        status:
          $ref: '#/components/schemas/OrderStatus'
        breakdown:
          $ref: '#/components/schemas/Breakdown'
        total:
          type: number

    CancelOrderResponse:
      type: object
      properties:
        orderId:
          type: string
        status:
          $ref: '#/components/schemas/OrderStatus'
        cancelledAt:
          type: string
          format: date-time

    ReceiptLine:
      type: object
      properties:
        description:
          type: string
        amount:
          type: number

    Receipt:
      type: object
      properties:
        receiptId:
          type: string
        orderId:
          type: string
        generatedAt:
          type: string
          format: date-time
        status:
          type: string
        originZone:
          type: string
        destinationZone:
          type: string
        serviceType:
          type: string
        packagesCount:
          type: integer
        lines:
          type: array
          items:
            $ref: '#/components/schemas/ReceiptLine'
        subtotal:
          type: number
        discount:
          type: number
        total:
          type: number
        insuranceEnabled:
          type: boolean
        declaredValue:
          type: number

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string
        details:
          type: array
          items:
            type: string
